

name: osmatrix


on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "os fingerprinting"
      run: hostnamectl status

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "check if server is virtual"
      run: Systeminfo | findstr /i model   
    - name: "check the PROCESSOR_ARCHITECTURE environment variable.64-bit systems will say AMD64 and 32-bit systems should say x86"
      run: wmic OS get OSArchitecture        

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "brew update"
      run: brew update      
    - name: "brew upgrade"
      run: brew upgrade
    - name: "check on brew version"
      run: brew --version   #Homebrew 2.5.12   
    - name: "brew cask list"
      run:   brew list --cask #Warning: Calling brew cask list is deprecated! Use brew list [--cask] instead.
    - name: "brew list"
      run: brew list #List all the installed formulas
    - name: "Get OS X System Version"
      run: sw_vers       
    - name: "Get Mac System Details with system_profiler"
      run: system_profiler | more  
    - name: "osfingerprinting"
      run: uname -a                           
    # - name: "brew doctor"
    #   run: |
    #     brew doctor #Check brew for potential problems         