

name: osmatrix


on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]
  schedule:
    - cron:  '*/15 * * * *'


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "os fingerprinting"
      run: hostnamectl status

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!