

name: osmatrix


on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]
  schedule:
    - cron:  '*/15 * * * *'


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "os fingerprinting"
      run: hostnamectl status

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "Run a one-line script"
      run: echo Hello, world!
    - name: "check if server is virtual"
      run: Systeminfo | findstr /i model   
    - name: "check the PROCESSOR_ARCHITECTURE environment variable.64-bit systems will say AMD64 and 32-bit systems should say x86"
      run: wmic OS get OSArchitecture        

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "Run a one-line script"
      run: echo Hello, world!
    - name: "check on brew version"
      run: brew --version      