# This is a basic workflow to help you get started with Actions

name: osmatrix

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "os fingerprinting"
      run: hostnamectl status
    # - name:"Create virtualenv"
    #   run: |
    #         python -V
    #         python3 -V
    #         pip3 --version
    #         pip3 install virtualenv
    #         virtualenv -p $(which python3) ~venvpy3
    #         source ~venvpy3/bin/activate
    #         pip install -r requirements.txt      
    # - name: linkerd minikube latest wo snaps latest
    #   run: |
    #         sudo make deploy-minikube-latest
    #         sudo make deploy-linkerd  
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!